title: BucketBook
description: Basketball stats tracking app - Track your game, elevate your play
url: https://bucket-book.com
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Default layout for pages
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "index.md"
    values:
      layout: default

# Exclude from build
exclude:
  - README.md
  - LICENSE
